"""create customers

Revision ID: 783a238ddff0
Revises: e513b9fc22f6
Create Date: 2025-09-18 00:53:41.687643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783a238ddff0'
down_revision = 'e513b9fc22f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
